### ISSUE TITLE
Github action에 자동병합 추가하기

### ISSUE THREAD

**Issue by GrangbelrLurain** [GrangbelrLurain/utilities#19]
```yaml
name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Enable Auto-Merge
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
```
